export { Navbar } from './Navbar';
export { Hero } from './Hero';
export { About } from './About';
export { Awards } from './Awards';
export { Publications } from './Publications';
export { Projects } from './Projects';
export { TechStack } from './TechStack';
export { Contact } from './Contact';
export { Footer } from './Footer';